fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ultranet_user:
    resource: "@UltranetUserBundle/Resources/config/routing.yml"
    prefix:   /user

ultranet_core:
    resource: "@UltranetCoreBundle/Resources/config/routing.yml"
    prefix:   /