<?php

namespace Ultranet\CoreBundle\Repository;

/**
 * ImageFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
