services:
#    utranet_core.example:
#        class: Utranet\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    ultranet.registration.form.type:
        class: Ultranet\UserBundle\Form\Type\UserType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ultranet_user_registration }
